#!/usr/bin/env bash

export LANG=pt_BR.UTF-8

# Dialogo do botão OK das caixas do Dialog.
ok="Pronto!"

# Dialogo do botão cancelar das caixas do Dialog.
cancel="Voltar"

# Titulo da caixa de seleção de Idioma.
selidioma="Idiomas"

# Titulo do menu da caixa de seleção de idioma.
escidioma="Escolha o seu idioma"

# Titulo da tela de seleção de layout de teclado.
sellayout="Layout de teclado"

# Titulo do menu da escolha do teclado.
seclayout="Escolha seu layout de teclado"

# Titulo da tela de seleção de GMT
selzone="Fuso horário"

# Titulo do menu da escolha de Fuso horário
seczone="Escolha o seu fuso horário"

# Titulo da tela inícial do instalador
msginstallarch="INSTALADOR DO ARCH LINUX BASE"

# Texto da caixa de mensagem do instalador
msginstall="Bem-vindo ao instalador do Arch Linux Base!"
