#!/usr/bin/env bash
#
#
# install-arch-dialog: Instala o Arch Linux
#
# Site:       N/A
# Autor:      Jefferson Santana
# Manutenção: Jefferson Santana
#
# ---------------------------------------------------------------------------------- #
#  Um instalador basico com dialog
#
#  Exemplos:
#      $ install-arch-dialog
#      Inícia o instalador
# ---------------------------------------------------------------------------------- #
# Histórico:
#
#   v0.0.1 02/06/2020, Jefferson:
#       - Início do programa
# ---------------------------------------------------------------------------------- #
# ---------------------------------------------------------------------------------- #
# Testado em:
#   bash     v5.0.17(1)-release
#   dialog   v1.3-20200327
# ---------------------------------------------------------------------------------- #
# Agradecimentos:
#
# ---------------------------------------------------------------------------------- #

# Primeira tela do instalador
lidioma=$(dialog --stdout                   \
	    --title "Instalador Arch Linux" \
	    --menu "Escolha o idioma do instalador"       \
	    10 45 0                         \
	    pt-br "Brasil"                  )

source pt-br

# Janela do mapa do teclado
dlayout=$(dialog --stdout \
	--title "$LMSG1" \
	--menu "$LMSG2" \
	0 0 0 \
	br-abnt2 "$LMSG7" \
	us "$LMSG8"            )

loadkeys $dlayout

dlocale=$(dialog --stdout \
	--title "$LMSG3" \
	--menu "$LMSG4" \
	0 0 0 \
	pt_BR.UTF-8 "$LMSG5" \
	en_US.UTF-8 "$LMSG6")

dtime=$(dialog --stdout \
	--title "$LMSG9" \
	--menu "$LMSG10" \
	0 0 10 \
	$(ls /usr/share/zoneinfo/ | sed 's/$/ o/'))

if  test -d /usr/share/zoneinfo/"$dtime"
	then
	dtime2=$(dialog --stdout \
		--title "$LMSG9" \
		--menu "$LMSG10" \
		0 0 10 \
		$(ls /usr/share/zoneinfo/"$dtime" | sed 's/$/ o/'))
	else
	ln -sf /usr/share/zoneinfo/"$dtime" /etc/localtime
	timedatectl set-ntp true
	dlocaltime=$(/usr/share/zoneinfo/"$dtime")

fi

if  test -d /usr/share/zoneinfo/"$dtime"/"$dtime2"
	then
		dtime3=$(dialog --stdout \
			--title "$LMSG9" \
			--menu "$LMSG10" \
			0 0 10 \
			$(ls /usr/share/zoneinfo/"$dtime"/"$dtime2" | sed 's/$/ o/'))
	else
		ln -sf /usr/share/zoneinfo/"$dtime"/"$dtime2" /etc/localtime
		timedatectl set-ntp true
	        dlocaltime=$(/usr/share/zoneinfo/"$dtime"/"$dtime2")
fi

clear ; echo "/usr/share/zoneinfo/"$dtime"/"$dtime2"/"$dtime3"" ; echo "$dlocaltime"
