#!/usr/bin/env bash

export LANG=pt_BR.UTF-8

# Janela do mapa do teclado
LMSG1="Configuração do teclado"

# Janela do mapa do teclado
LMSG2="Escolha o mapa do Teclado"

# Janela do mapa do teclado
LMSG3="Portugues BR"

# Janela do mapa do teclado
LMSG4="English US"

# Janela de localização do sistema
LMSG5="Localização"

# Janela de localização do sistema
LMSG6="Qual seu país"

# Janela de localização do sistema
LMSG7="Brasil"

# Janela de localização do sistema
LMSG8="EUA"

# Janela de timezone
LMSG9="Configuração de Timezone"

# Janela de timezone
LMSG10="Escolha sua Timezone"
