#!/usr/bin/env bash

fuidioma () {

	didioma=$(dialog \
		--stdout \
		--nocancel \
		--ok-label "$ok" \
		--title "$selidioma" \
		--menu "$escidioma" \
		0 0 10 \
		pt-br "Potuguẽs BR" )	
	source language/"$didioma"
}

fulayout () {

	teclayout=$(dialog \
		--stdout \
		--cancel-label "$cancel" \
		--ok-label "$ok" \
		--title "$sellayout" \
		--menu "$seclayout" 0 0 10 br "Brasil")
	#localectl set-keymap br
}

fuzoneinfo () {

	dzoneinfo=$(dialog \
		--stdout \
		--cancel-label "$cancel" \
		--ok-label "$ok" \
		--title "$selzone" \
		--menu "$seczone" \
		0 0 10 \
		$zonelist)
	if (find /usr/share/zoneinfo -maxdepth 1 -type d | sed -n -e 's!^.*/!!p' | grep "$dzoneinfo" &> /dev/null); then
		sublist=$(find /usr/share/zoneinfo/"$dzoneinfo" -maxdepth 1 | sed -n -e 's!^.*/!!p' | sort | sed 's/$/ -/g' | grep -v "$dzoneinfo")
		dsubzoneinfo=$(dialog --stdout --ok-label "$ok" --cancel-label "$cancel" --title "$selzone" --menu "$seczone" 0 0 10 $sublist)
		if [[ "$?" -eq "0" ]]; then
			if (find /usr/share/zoneinfo/"$dzoneinfo" -maxdepth 1 -type  d | sed -n -e 's!^.*/!!p' | grep "$dsubzoneinfo" &> /dev/null); then
			sublist=$(find /usr/share/zoneinfo/"$dzoneinfo"/"$dsubzoneinfo" -maxdepth 1 | sed -n -e 's!^.*/!!p' | sort | sed 's/$/ -/g' | grep -v "$dsubzoneinfo")
                    dnsubzone=$(dialog --stdout --ok-label "$ok" --cancel-label "$cancel" --title "$selzone" --menu "$seczone" 0 0 10 $sublist)
                    if [ "$?" -eq "0" ]; then
                        dzoneinfo="${dzoneinfo}/${dsubzoneinfo}/${dnsubzone}"
                    fi	
		else
			dzoneinfo="${dzoneinfo}/${dsubzoneinfo}"
				
			fi
		fi
	fi
}
